### ISSUE TITLE
Compilation doesn't work on macOS

### ISSUE THREAD

**Issue by jdpopkin** [dozzie/toml#1]
Hi there! Compilation doesn't work on macOS because both the `Makefile` and `rebar.config`'s post-compile hook involve commands that won't work with the BSD `sed` that ships with macOS. I have a PR that works on macOS; I'll try it on Linux later tonight. There are two `sed`-related issues that break this library on macOS:

## In-place editing with BSD sed
`sed -i` with no argument doesn't work on macOS. You can accomplish the same thing with `sed -i ''`, but that doesn't work with GNU sed.

## The `i` command
`sed -e `1ifoo'` doesn't work on macOS. Instead, the `i` command must be followed by a `\` and a newline, with the text to be inserted on the following line. Unfortunately, _that_ doesn't seem to work in a Makefile: a line ending in a single backslash will produce an escaped newline; guessing based on the errors I see, a line ending in two backslashes appears to produce two backslashes.

You can work around the first problem using `sed -i.bak [...] && rm $@.bak`. The second problem is a little bit messier - you can't build the exact string you want to use, but you can build _parts_ of it, then use the shell to put things back together.

**Comment by dozzie** [comment]
Thanks for the report. I've never cared about macOS support, because I don't have any Apple hardware. Though the rules don't work under FreeBSD, either, and this fact is important enough for me. The rest of the work in #2.
